name: macOS

on:
  push:
    branches:
      - develop
      - main
      - release/*
  pull_request:
  workflow_dispatch:

jobs:
  xcode_standards:
    runs-on: macos-latest
    strategy:
      matrix:
        standard: [11, 14, 17, 20]
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

    steps:
      - uses: actions/checkout@v3
      - name: CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DTPH_BuildTests=On -DCMAKE_CXX_STANDARD=${{ matrix.standard }}
#        run: cmake --preset=${{ matrix.compiler }}-ci -S . -DCMAKE_CXX_STANDARD=${{ matrix.standard }}
      - name: Build
        run: cmake --build build --parallel 10
#        run: cmake --build --preset=${{ matrix.compiler }}-ci


      # - name: cmake
      #   run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug -DJSON_BuildTests=On -DJSON_TestStandards=${{ matrix.standard }}
      # - name: build
      #   run: cmake --build build --parallel 10
      # - name: test
      #   run: cd build ; ctest -j 10 --output-on-failure