name: ubuntu

on:
  push:
    branches:
      - develop
      - main
      - release/*
  pull_request:
  workflow_dispatch:

jobs:
  ci_test_standards:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        standard: [11, 14, 17, 20]
    steps:
      - uses: actions/checkout@v3
      - name: (gcc) Use gcc-10 
        if: matrix.compiler == 'gcc'
        run: |
          sudo apt install gcc-10 g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
          sudo update-alternatives --set gcc /usr/bin/gcc-10        
      - name: Use clang-12
        if: matrix.compiler == 'clang'
        run: |
          sudo apt install clang-12
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-12 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-12 100
          sudo update-alternatives --set clang /usr/bin/clang-12        
          sudo update-alternatives --set clang++ /usr/bin/clang++-12        
      - name: CMake
        run: cmake --preset=${{ matrix.compiler }}-ci -S . -DCMAKE_CXX_STANDARD=${{ matrix.standard }}
      - name: Build
        run: cmake --build --preset=${{ matrix.compiler }}-ci
