name: Windows

on:
  push:
    branches:
      - develop
      - main
      - release/*
  pull_request:
  workflow_dispatch:

jobs:
  msvc2022:
    runs-on: windows-2022
    strategy:
      matrix:
        build_type: [Debug, Release]
        architecture: [Win32, x64]

    steps:
    - uses: actions/checkout@v3
    - name: CMake
      run: cmake -S . -B build -G "Visual Studio 17 2022" -A ${{ matrix.architecture }} -DTPH_BuildTests=On -DCMAKE_CXX_FLAGS="/permissive- /std:c++latest /utf-8 /W4 /WX"
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --parallel 10
